# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_pointsofinterest_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsofinterest',
            name='points',
            field=models.TextField(default=''),
        ),
    ]
